// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS-NOjfhCNS6zZ8MNimyZpeEVV_QzMC8M',
    appId: '1:999737237509:web:78acb7f42fbea2a5dc7c6c',
    messagingSenderId: '999737237509',
    projectId: 'rentzyyyy',
    authDomain: 'rentzyyyy.firebaseapp.com',
    storageBucket: 'rentzyyyy.appspot.com',
    measurementId: 'G-40N0BPNVVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6HpNK3G75Zw3mwybUSwkFhinMxWcJ7BQ',
    appId: '1:999737237509:android:d6e2dccba4c7d9badc7c6c',
    messagingSenderId: '999737237509',
    projectId: 'rentzyyyy',
    storageBucket: 'rentzyyyy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaGOpmMgsW5yfHh5RGS9VWNERaMXg9_QA',
    appId: '1:999737237509:ios:311f70e807c092eedc7c6c',
    messagingSenderId: '999737237509',
    projectId: 'rentzyyyy',
    storageBucket: 'rentzyyyy.appspot.com',
    iosBundleId: 'com.example.rentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaGOpmMgsW5yfHh5RGS9VWNERaMXg9_QA',
    appId: '1:999737237509:ios:311f70e807c092eedc7c6c',
    messagingSenderId: '999737237509',
    projectId: 'rentzyyyy',
    storageBucket: 'rentzyyyy.appspot.com',
    iosBundleId: 'com.example.rentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS-NOjfhCNS6zZ8MNimyZpeEVV_QzMC8M',
    appId: '1:999737237509:web:d17a22261ef27f67dc7c6c',
    messagingSenderId: '999737237509',
    projectId: 'rentzyyyy',
    authDomain: 'rentzyyyy.firebaseapp.com',
    storageBucket: 'rentzyyyy.appspot.com',
    measurementId: 'G-G0DNZPQH4H',
  );
}
